version: '3.7'

services:
  taxi-redis:
    container_name: taxi-redis
    image: redis:5.0.7-alpine

  taxi-database:
    container_name: taxi-database
    environment:
        POSTGRES_DB: docker
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
    restart: always
    build:
     context: ./server
     dockerfile: Dockerfile.psql
    volumes:
      - $home/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  taxi-server:
    build:
      context: ./server
    command: python taxi/manage.py runserver 0.0.0.0:8000
    container_name: taxi-server
    depends_on:
      - taxi-redis
      - taxi-database
    env_file:
      - ./server/dev.env
    ports:
      - 8001:8000

volumes:
  taxi-database:
