version: '3.7'

services:
  taxi-redis:
    container_name: taxi-redis
    image: redis:5.0.7-alpine

  taxi-database:
    container_name: taxi-database
    environment:
        POSTGRES_DB: docker
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
    restart: always
    build:
     context: ./server
     dockerfile: Dockerfile.psql
    volumes:
      - taxi-database:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  taxi-server:
    build:
      context: ./server
    volumes:  # new
      - media:/usr/src/app/media
      - static:/usr/src/app/static
    command: daphne --bind 0.0.0.0 --port 8000 taxi.asgi:application
    #command: python taxi/manage.py runserver 0.0.0.0:8000
    container_name: taxi-server
    depends_on:
      - taxi-redis
      - taxi-database
    env_file:
      #- ./server/test.env
      - ./server/dev.env
    ports:
      - 8001:8000

  taxi-client:
    build:
      context: ./client
    command: npm start
    container_name: taxi-client
    depends_on:
      - taxi-server
    ports:
      - 3001:3000
    # this is temporal fix, to be removed
    stdin_open: true

  taxi-nginx:
    build:
      context: ./nginx
    container_name: taxi-nginx
    depends_on:
      - taxi-server
      - taxi-client
    ports:
      - 8080:80
    restart: always
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static

volumes:
  taxi-database:
  media:
  static:
